muutuja:     !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30343965383436613931643130333237633863303965326465346364623562376531386435333334
          3139623137333861613630336531323739643263393534330a323239353162346131663332623362
          39643566336264383739323131663461626663306231633566653234623239366339663465623530
          6432303362353630330a343038396138313963353238303138366562333765343836633231666265
          3665